---
name: CPSP-workshop
on: null
push: null
branches:
  - master
jobs: null
scan: null
runs-on: ubuntu-latest
strategy: null
matrix: null
python-version:
  - 3.8
steps:
  - name: Run Bridgecrew
id: Bridgecrew
uses: bridgecrewio/bridgecrew-action@master
env: null
PRISMA_API_URL: https://api3.prismacloud.io
with: null
api-key: ${{ secrets.BC_API_KEY }}
